kind: IdentifyAndAuthorize
apiVersion: api.webmethods.io/beta
metadata:
  name: TokenPolicy
  namespace: TestProject
  version: '1.0'
  tags: []
spec:
  identificationType:
    or:
      apiKey:
        applicationLookup: registered
